### ISSUE TITLE
Trouble getting set up

### ISSUE THREAD

**Issue by jhanstra** [awitherow/coinbot#27]
Error:
```
▲ yarn run go
yarn run v0.20.3
$ node index.js
/Users/jhanstra/JH/learn/coin/coinbot/src/index.js:57
async function run(currency        ) {
      ^^^^^^^^
SyntaxError: Unexpected token function
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Module._compile (/Users/jhanstra/JH/learn/coin/coinbot/node_modules/flow-remove-types/register.js:29:23)
    at Module._extensions..js (module.js:579:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/jhanstra/JH/learn/coin/coinbot/node_modules/flow-remove-types/register.js:32:5)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Is this a babel error?

**Comment by awitherow** [comment]
This project does not use babel.

Please read the second on the README about requirements for the node version.

https://github.com/awitherow/coinbot/blob/master/README.md#requirements

If you use nvm, you can easily type `nvm use` or `nvm install` before running the application and it will ensure you are on the correct node version.

**Comment by awitherow** [comment]
Please document any of your further setup errors in this issue and hopefully I can clarify these Q&A style for future people setting up!

**Comment by awitherow** [comment]
@jhanstra any luck?

**Comment by jhanstra** [comment]
Hey @awitherow, got busy with other things. I'm set up! I think. Not sure if my twilio is set up correctly, but the program is running in the console. Still browsing through the code and trying to understand everything.

Once I have a good feel for what's going on I'll try to work on it and submit some PRs - I just forked the main repo.

**Comment by awitherow** [comment]
I pushed a hot fix for twilio, it was not sending messages correctly. Twilio is not a required functionality if you do not have it already, fyi.

Thanks for checking this out 👍 

Check out the main dependency as well, https://github.com/coinbase/gdax-node

Would love to try to get more people looking into fixing this up.
